// Generated by `dotnet new wasmbrowser` and kept verbatim. It is not boilerplate: [JSExport] and
// [JSImport] are annotated [SupportedOSPlatform("browser")], so without this attribute CA1416 fails
// the build with "This call site is reachable on all platforms. 'JSExportAttribute' is only
// supported on: 'browser'". Setting <RuntimeIdentifier>browser-wasm</RuntimeIdentifier> does NOT
// substitute for it - measured 2026-09-18, the RID alone leaves CA1416 red.
[assembly: System.Runtime.Versioning.SupportedOSPlatform("browser")]
