// <auto-generated/>
// Transliterated from upstream/src/_regex_unicode.h by tools/transliterate-unicode.py.
// Do not edit by hand: re-run the script instead.
#nullable enable

namespace Fuzzy.Text.RegularExpressions.Unicode;

internal static partial class UnicodeTables
{
    /// <summary>Upstream <c>RE_UNICODE_VERSION</c>.</summary>
    internal const string UnicodeVersion = "17.0.0";
    /// <summary>Upstream <c>RE_ASCII_MAX</c>.</summary>
    internal const int AsciiMax = 0x7F;
    /// <summary>Upstream <c>RE_LOCALE_MAX</c>.</summary>
    internal const int LocaleMax = 0xFF;
    /// <summary>Upstream <c>RE_MAX_CASES</c>.</summary>
    internal const int MaxCases = 4;
    /// <summary>Upstream <c>RE_MAX_FOLDED</c>.</summary>
    internal const int MaxFolded = 3;
    /// <summary>Upstream <c>RE_MAX_SCX</c>.</summary>
    internal const int MaxScx = 23;
    /// <summary>Upstream <c>RE_PROP_GC</c>.</summary>
    internal const int PropGc = 0x1E;
    /// <summary>Upstream <c>RE_PROP_CASED</c>.</summary>
    internal const int PropCased = 0xA;
    /// <summary>Upstream <c>RE_PROP_UPPERCASE</c>.</summary>
    internal const int PropUppercase = 0x5C;
    /// <summary>Upstream <c>RE_PROP_LOWERCASE</c>.</summary>
    internal const int PropLowercase = 0x38;
    /// <summary>Upstream <c>RE_PROP_SCX</c>.</summary>
    internal const int PropScx = 0x56;
    /// <summary>Upstream <c>RE_PROP_C</c>.</summary>
    internal const int PropC = 30;
    /// <summary>Upstream <c>RE_PROP_L</c>.</summary>
    internal const int PropL = 31;
    /// <summary>Upstream <c>RE_PROP_M</c>.</summary>
    internal const int PropM = 32;
    /// <summary>Upstream <c>RE_PROP_N</c>.</summary>
    internal const int PropN = 33;
    /// <summary>Upstream <c>RE_PROP_P</c>.</summary>
    internal const int PropP = 34;
    /// <summary>Upstream <c>RE_PROP_S</c>.</summary>
    internal const int PropS = 35;
    /// <summary>Upstream <c>RE_PROP_Z</c>.</summary>
    internal const int PropZ = 36;
    /// <summary>Upstream <c>RE_PROP_ASSIGNED</c>.</summary>
    internal const int PropAssigned = 37;
    /// <summary>Upstream <c>RE_PROP_CASEDLETTER</c>.</summary>
    internal const int PropCasedletter = 38;
    /// <summary>Upstream <c>RE_PROP_CN</c>.</summary>
    internal const int PropCn = 0;
    /// <summary>Upstream <c>RE_PROP_CC</c>.</summary>
    internal const int PropCc = 1;
    /// <summary>Upstream <c>RE_PROP_ZS</c>.</summary>
    internal const int PropZs = 2;
    /// <summary>Upstream <c>RE_PROP_PO</c>.</summary>
    internal const int PropPo = 3;
    /// <summary>Upstream <c>RE_PROP_SC</c>.</summary>
    internal const int PropSc = 4;
    /// <summary>Upstream <c>RE_PROP_PS</c>.</summary>
    internal const int PropPs = 5;
    /// <summary>Upstream <c>RE_PROP_PE</c>.</summary>
    internal const int PropPe = 6;
    /// <summary>Upstream <c>RE_PROP_SM</c>.</summary>
    internal const int PropSm = 7;
    /// <summary>Upstream <c>RE_PROP_PD</c>.</summary>
    internal const int PropPd = 8;
    /// <summary>Upstream <c>RE_PROP_ND</c>.</summary>
    internal const int PropNd = 9;
    /// <summary>Upstream <c>RE_PROP_LU</c>.</summary>
    internal const int PropLu = 10;
    /// <summary>Upstream <c>RE_PROP_SK</c>.</summary>
    internal const int PropSk = 11;
    /// <summary>Upstream <c>RE_PROP_PC</c>.</summary>
    internal const int PropPc = 12;
    /// <summary>Upstream <c>RE_PROP_LL</c>.</summary>
    internal const int PropLl = 13;
    /// <summary>Upstream <c>RE_PROP_SO</c>.</summary>
    internal const int PropSo = 14;
    /// <summary>Upstream <c>RE_PROP_LO</c>.</summary>
    internal const int PropLo = 15;
    /// <summary>Upstream <c>RE_PROP_PI</c>.</summary>
    internal const int PropPi = 16;
    /// <summary>Upstream <c>RE_PROP_CF</c>.</summary>
    internal const int PropCf = 17;
    /// <summary>Upstream <c>RE_PROP_NO</c>.</summary>
    internal const int PropNo = 18;
    /// <summary>Upstream <c>RE_PROP_PF</c>.</summary>
    internal const int PropPf = 19;
    /// <summary>Upstream <c>RE_PROP_LT</c>.</summary>
    internal const int PropLt = 20;
    /// <summary>Upstream <c>RE_PROP_LM</c>.</summary>
    internal const int PropLm = 21;
    /// <summary>Upstream <c>RE_PROP_MN</c>.</summary>
    internal const int PropMn = 22;
    /// <summary>Upstream <c>RE_PROP_ME</c>.</summary>
    internal const int PropMe = 23;
    /// <summary>Upstream <c>RE_PROP_MC</c>.</summary>
    internal const int PropMc = 24;
    /// <summary>Upstream <c>RE_PROP_NL</c>.</summary>
    internal const int PropNl = 25;
    /// <summary>Upstream <c>RE_PROP_ZL</c>.</summary>
    internal const int PropZl = 26;
    /// <summary>Upstream <c>RE_PROP_ZP</c>.</summary>
    internal const int PropZp = 27;
    /// <summary>Upstream <c>RE_PROP_CS</c>.</summary>
    internal const int PropCs = 28;
    /// <summary>Upstream <c>RE_PROP_CO</c>.</summary>
    internal const int PropCo = 29;
    /// <summary>Upstream <c>RE_PROP_C_MASK</c>.</summary>
    internal const int PropCMask = 0x30020003;
    /// <summary>Upstream <c>RE_PROP_L_MASK</c>.</summary>
    internal const int PropLMask = 0x0030A400;
    /// <summary>Upstream <c>RE_PROP_M_MASK</c>.</summary>
    internal const int PropMMask = 0x01C00000;
    /// <summary>Upstream <c>RE_PROP_N_MASK</c>.</summary>
    internal const int PropNMask = 0x02040200;
    /// <summary>Upstream <c>RE_PROP_P_MASK</c>.</summary>
    internal const int PropPMask = 0x00091168;
    /// <summary>Upstream <c>RE_PROP_S_MASK</c>.</summary>
    internal const int PropSMask = 0x00004890;
    /// <summary>Upstream <c>RE_PROP_Z_MASK</c>.</summary>
    internal const int PropZMask = 0x0C000004;
    /// <summary>Upstream <c>RE_PROP_ALNUM</c>.</summary>
    internal const int PropAlnum = 0x010001;
    /// <summary>Upstream <c>RE_PROP_ALPHA</c>.</summary>
    internal const int PropAlpha = 0x000001;
    /// <summary>Upstream <c>RE_PROP_ANY</c>.</summary>
    internal const int PropAny = 0x020001;
    /// <summary>Upstream <c>RE_PROP_ASCII</c>.</summary>
    internal const int PropAscii = 0x080001;
    /// <summary>Upstream <c>RE_PROP_BLANK</c>.</summary>
    internal const int PropBlank = 0x070001;
    /// <summary>Upstream <c>RE_PROP_CNTRL</c>.</summary>
    internal const int PropCntrl = 0x1E0001;
    /// <summary>Upstream <c>RE_PROP_DIGIT</c>.</summary>
    internal const int PropDigit = 0x1E0009;
    /// <summary>Upstream <c>RE_PROP_GRAPH</c>.</summary>
    internal const int PropGraph = 0x1F0001;
    /// <summary>Upstream <c>RE_PROP_LOWER</c>.</summary>
    internal const int PropLower = 0x380001;
    /// <summary>Upstream <c>RE_PROP_PRINT</c>.</summary>
    internal const int PropPrint = 0x510001;
    /// <summary>Upstream <c>RE_PROP_SPACE</c>.</summary>
    internal const int PropSpace = 0x5F0001;
    /// <summary>Upstream <c>RE_PROP_UPPER</c>.</summary>
    internal const int PropUpper = 0x5C0001;
    /// <summary>Upstream <c>RE_PROP_WORD</c>.</summary>
    internal const int PropWord = 0x600001;
    /// <summary>Upstream <c>RE_PROP_XDIGIT</c>.</summary>
    internal const int PropXdigit = 0x620001;
    /// <summary>Upstream <c>RE_PROP_POSIX_ALNUM</c>.</summary>
    internal const int PropPosixAlnum = 0x4C0001;
    /// <summary>Upstream <c>RE_PROP_POSIX_DIGIT</c>.</summary>
    internal const int PropPosixDigit = 0x4D0001;
    /// <summary>Upstream <c>RE_PROP_POSIX_PUNCT</c>.</summary>
    internal const int PropPosixPunct = 0x4E0001;
    /// <summary>Upstream <c>RE_PROP_POSIX_XDIGIT</c>.</summary>
    internal const int PropPosixXdigit = 0x4F0001;
    /// <summary>Upstream <c>RE_WBREAK_OTHER</c>.</summary>
    internal const int WbreakOther = 0;
    /// <summary>Upstream <c>RE_WBREAK_LF</c>.</summary>
    internal const int WbreakLf = 1;
    /// <summary>Upstream <c>RE_WBREAK_NEWLINE</c>.</summary>
    internal const int WbreakNewline = 2;
    /// <summary>Upstream <c>RE_WBREAK_CR</c>.</summary>
    internal const int WbreakCr = 3;
    /// <summary>Upstream <c>RE_WBREAK_WSEGSPACE</c>.</summary>
    internal const int WbreakWsegspace = 4;
    /// <summary>Upstream <c>RE_WBREAK_DOUBLEQUOTE</c>.</summary>
    internal const int WbreakDoublequote = 5;
    /// <summary>Upstream <c>RE_WBREAK_SINGLEQUOTE</c>.</summary>
    internal const int WbreakSinglequote = 6;
    /// <summary>Upstream <c>RE_WBREAK_MIDNUM</c>.</summary>
    internal const int WbreakMidnum = 7;
    /// <summary>Upstream <c>RE_WBREAK_MIDNUMLET</c>.</summary>
    internal const int WbreakMidnumlet = 8;
    /// <summary>Upstream <c>RE_WBREAK_NUMERIC</c>.</summary>
    internal const int WbreakNumeric = 9;
    /// <summary>Upstream <c>RE_WBREAK_MIDLETTER</c>.</summary>
    internal const int WbreakMidletter = 10;
    /// <summary>Upstream <c>RE_WBREAK_ALETTER</c>.</summary>
    internal const int WbreakAletter = 11;
    /// <summary>Upstream <c>RE_WBREAK_EXTENDNUMLET</c>.</summary>
    internal const int WbreakExtendnumlet = 12;
    /// <summary>Upstream <c>RE_WBREAK_FORMAT</c>.</summary>
    internal const int WbreakFormat = 13;
    /// <summary>Upstream <c>RE_WBREAK_EXTEND</c>.</summary>
    internal const int WbreakExtend = 14;
    /// <summary>Upstream <c>RE_WBREAK_HEBREWLETTER</c>.</summary>
    internal const int WbreakHebrewletter = 15;
    /// <summary>Upstream <c>RE_WBREAK_ZWJ</c>.</summary>
    internal const int WbreakZwj = 16;
    /// <summary>Upstream <c>RE_WBREAK_KATAKANA</c>.</summary>
    internal const int WbreakKatakana = 17;
    /// <summary>Upstream <c>RE_WBREAK_REGIONALINDICATOR</c>.</summary>
    internal const int WbreakRegionalindicator = 18;
    /// <summary>Upstream <c>RE_WBREAK_EBASE</c>.</summary>
    internal const int WbreakEbase = 19;
    /// <summary>Upstream <c>RE_WBREAK_EBASEGAZ</c>.</summary>
    internal const int WbreakEbasegaz = 20;
    /// <summary>Upstream <c>RE_WBREAK_EMODIFIER</c>.</summary>
    internal const int WbreakEmodifier = 21;
    /// <summary>Upstream <c>RE_WBREAK_GLUEAFTERZWJ</c>.</summary>
    internal const int WbreakGlueafterzwj = 22;
    /// <summary>Upstream <c>RE_GBREAK_OTHER</c>.</summary>
    internal const int GbreakOther = 0;
    /// <summary>Upstream <c>RE_GBREAK_CONTROL</c>.</summary>
    internal const int GbreakControl = 1;
    /// <summary>Upstream <c>RE_GBREAK_LF</c>.</summary>
    internal const int GbreakLf = 2;
    /// <summary>Upstream <c>RE_GBREAK_CR</c>.</summary>
    internal const int GbreakCr = 3;
    /// <summary>Upstream <c>RE_GBREAK_EXTEND</c>.</summary>
    internal const int GbreakExtend = 4;
    /// <summary>Upstream <c>RE_GBREAK_PREPEND</c>.</summary>
    internal const int GbreakPrepend = 5;
    /// <summary>Upstream <c>RE_GBREAK_SPACINGMARK</c>.</summary>
    internal const int GbreakSpacingmark = 6;
    /// <summary>Upstream <c>RE_GBREAK_L</c>.</summary>
    internal const int GbreakL = 7;
    /// <summary>Upstream <c>RE_GBREAK_V</c>.</summary>
    internal const int GbreakV = 8;
    /// <summary>Upstream <c>RE_GBREAK_T</c>.</summary>
    internal const int GbreakT = 9;
    /// <summary>Upstream <c>RE_GBREAK_ZWJ</c>.</summary>
    internal const int GbreakZwj = 10;
    /// <summary>Upstream <c>RE_GBREAK_LV</c>.</summary>
    internal const int GbreakLv = 11;
    /// <summary>Upstream <c>RE_GBREAK_LVT</c>.</summary>
    internal const int GbreakLvt = 12;
    /// <summary>Upstream <c>RE_GBREAK_REGIONALINDICATOR</c>.</summary>
    internal const int GbreakRegionalindicator = 13;
    /// <summary>Upstream <c>RE_GBREAK_EBASE</c>.</summary>
    internal const int GbreakEbase = 14;
    /// <summary>Upstream <c>RE_GBREAK_EBASEGAZ</c>.</summary>
    internal const int GbreakEbasegaz = 15;
    /// <summary>Upstream <c>RE_GBREAK_EMODIFIER</c>.</summary>
    internal const int GbreakEmodifier = 16;
    /// <summary>Upstream <c>RE_GBREAK_GLUEAFTERZWJ</c>.</summary>
    internal const int GbreakGlueafterzwj = 17;
    /// <summary>Upstream <c>RE_LBREAK_UNKNOWN</c>.</summary>
    internal const int LbreakUnknown = 0;
    /// <summary>Upstream <c>RE_LBREAK_COMBININGMARK</c>.</summary>
    internal const int LbreakCombiningmark = 1;
    /// <summary>Upstream <c>RE_LBREAK_BREAKAFTER</c>.</summary>
    internal const int LbreakBreakafter = 2;
    /// <summary>Upstream <c>RE_LBREAK_LINEFEED</c>.</summary>
    internal const int LbreakLinefeed = 3;
    /// <summary>Upstream <c>RE_LBREAK_MANDATORYBREAK</c>.</summary>
    internal const int LbreakMandatorybreak = 4;
    /// <summary>Upstream <c>RE_LBREAK_CARRIAGERETURN</c>.</summary>
    internal const int LbreakCarriagereturn = 5;
    /// <summary>Upstream <c>RE_LBREAK_SPACE</c>.</summary>
    internal const int LbreakSpace = 6;
    /// <summary>Upstream <c>RE_LBREAK_EXCLAMATION</c>.</summary>
    internal const int LbreakExclamation = 7;
    /// <summary>Upstream <c>RE_LBREAK_QUOTATION</c>.</summary>
    internal const int LbreakQuotation = 8;
    /// <summary>Upstream <c>RE_LBREAK_ALPHABETIC</c>.</summary>
    internal const int LbreakAlphabetic = 9;
    /// <summary>Upstream <c>RE_LBREAK_PREFIXNUMERIC</c>.</summary>
    internal const int LbreakPrefixnumeric = 10;
    /// <summary>Upstream <c>RE_LBREAK_POSTFIXNUMERIC</c>.</summary>
    internal const int LbreakPostfixnumeric = 11;
    /// <summary>Upstream <c>RE_LBREAK_OPENPUNCTUATION</c>.</summary>
    internal const int LbreakOpenpunctuation = 12;
    /// <summary>Upstream <c>RE_LBREAK_CLOSEPARENTHESIS</c>.</summary>
    internal const int LbreakCloseparenthesis = 13;
    /// <summary>Upstream <c>RE_LBREAK_INFIXNUMERIC</c>.</summary>
    internal const int LbreakInfixnumeric = 14;
    /// <summary>Upstream <c>RE_LBREAK_HYPHEN</c>.</summary>
    internal const int LbreakHyphen = 15;
    /// <summary>Upstream <c>RE_LBREAK_BREAKSYMBOLS</c>.</summary>
    internal const int LbreakBreaksymbols = 16;
    /// <summary>Upstream <c>RE_LBREAK_NUMERIC</c>.</summary>
    internal const int LbreakNumeric = 17;
    /// <summary>Upstream <c>RE_LBREAK_CLOSEPUNCTUATION</c>.</summary>
    internal const int LbreakClosepunctuation = 18;
    /// <summary>Upstream <c>RE_LBREAK_NEXTLINE</c>.</summary>
    internal const int LbreakNextline = 19;
    /// <summary>Upstream <c>RE_LBREAK_GLUE</c>.</summary>
    internal const int LbreakGlue = 20;
    /// <summary>Upstream <c>RE_LBREAK_AMBIGUOUS</c>.</summary>
    internal const int LbreakAmbiguous = 21;
    /// <summary>Upstream <c>RE_LBREAK_BREAKBEFORE</c>.</summary>
    internal const int LbreakBreakbefore = 22;
    /// <summary>Upstream <c>RE_LBREAK_UNAMBIGUOUSHYPHEN</c>.</summary>
    internal const int LbreakUnambiguoushyphen = 23;
    /// <summary>Upstream <c>RE_LBREAK_HEBREWLETTER</c>.</summary>
    internal const int LbreakHebrewletter = 24;
    /// <summary>Upstream <c>RE_LBREAK_COMPLEXCONTEXT</c>.</summary>
    internal const int LbreakComplexcontext = 25;
    /// <summary>Upstream <c>RE_LBREAK_JL</c>.</summary>
    internal const int LbreakJl = 26;
    /// <summary>Upstream <c>RE_LBREAK_JV</c>.</summary>
    internal const int LbreakJv = 27;
    /// <summary>Upstream <c>RE_LBREAK_JT</c>.</summary>
    internal const int LbreakJt = 28;
    /// <summary>Upstream <c>RE_LBREAK_NONSTARTER</c>.</summary>
    internal const int LbreakNonstarter = 29;
    /// <summary>Upstream <c>RE_LBREAK_AKSARA</c>.</summary>
    internal const int LbreakAksara = 30;
    /// <summary>Upstream <c>RE_LBREAK_VIRAMA</c>.</summary>
    internal const int LbreakVirama = 31;
    /// <summary>Upstream <c>RE_LBREAK_AKSARASTART</c>.</summary>
    internal const int LbreakAksarastart = 32;
    /// <summary>Upstream <c>RE_LBREAK_IDEOGRAPHIC</c>.</summary>
    internal const int LbreakIdeographic = 33;
    /// <summary>Upstream <c>RE_LBREAK_VIRAMAFINAL</c>.</summary>
    internal const int LbreakViramafinal = 34;
    /// <summary>Upstream <c>RE_LBREAK_ZWSPACE</c>.</summary>
    internal const int LbreakZwspace = 35;
    /// <summary>Upstream <c>RE_LBREAK_ZWJ</c>.</summary>
    internal const int LbreakZwj = 36;
    /// <summary>Upstream <c>RE_LBREAK_BREAKBOTH</c>.</summary>
    internal const int LbreakBreakboth = 37;
    /// <summary>Upstream <c>RE_LBREAK_INSEPARABLE</c>.</summary>
    internal const int LbreakInseparable = 38;
    /// <summary>Upstream <c>RE_LBREAK_WORDJOINER</c>.</summary>
    internal const int LbreakWordjoiner = 39;
    /// <summary>Upstream <c>RE_LBREAK_EBASE</c>.</summary>
    internal const int LbreakEbase = 40;
    /// <summary>Upstream <c>RE_LBREAK_CONDITIONALJAPANESESTARTER</c>.</summary>
    internal const int LbreakConditionaljapanesestarter = 41;
    /// <summary>Upstream <c>RE_LBREAK_H2</c>.</summary>
    internal const int LbreakH2 = 42;
    /// <summary>Upstream <c>RE_LBREAK_H3</c>.</summary>
    internal const int LbreakH3 = 43;
    /// <summary>Upstream <c>RE_LBREAK_SURROGATE</c>.</summary>
    internal const int LbreakSurrogate = 44;
    /// <summary>Upstream <c>RE_LBREAK_CONTINGENTBREAK</c>.</summary>
    internal const int LbreakContingentbreak = 45;
    /// <summary>Upstream <c>RE_LBREAK_AKSARAPREBASE</c>.</summary>
    internal const int LbreakAksaraprebase = 46;
    /// <summary>Upstream <c>RE_LBREAK_REGIONALINDICATOR</c>.</summary>
    internal const int LbreakRegionalindicator = 47;
    /// <summary>Upstream <c>RE_LBREAK_EMODIFIER</c>.</summary>
    internal const int LbreakEmodifier = 48;
    /// <summary>Upstream <c>RE_INCB_NONE</c>.</summary>
    internal const int IncbNone = 0;
    /// <summary>Upstream <c>RE_INCB_EXTEND</c>.</summary>
    internal const int IncbExtend = 1;
    /// <summary>Upstream <c>RE_INCB_CONSONANT</c>.</summary>
    internal const int IncbConsonant = 2;
    /// <summary>Upstream <c>RE_INCB_LINKER</c>.</summary>
    internal const int IncbLinker = 3;
    /// <summary>Upstream <c>RE_BLANK_MASK</c>.</summary>
    internal const int BlankMask = ((1 << PropZl) | (1 << PropZp));
    /// <summary>Upstream <c>RE_GRAPH_MASK</c>.</summary>
    internal const int GraphMask = ((1 << PropCc) | (1 << PropCs) | (1 << PropCn));
    /// <summary>Upstream <c>RE_WORD_MASK</c>.</summary>
    internal const int WordMask = (PropMMask | (1 << PropNd) | (1 << PropPc));
}
