// <auto-generated/>
// Transliterated from upstream/src/_regex_unicode.c by tools/transliterate-unicode.py.
// Do not edit by hand: re-run the script instead.
#nullable enable

namespace Fuzzy.Text.RegularExpressions.Unicode;

internal static partial class UnicodeTables
{
    /// <summary>
    /// Every numeric table, keyed by its name in the C source, so a test can walk them
    /// all and check each one against a digest taken independently from that source.
    /// A table that was one struct array in C appears once per field.
    /// </summary>
    /// <returns>The tables, in the order the C file declares them.</returns>
    internal static List<(string Name, uint[] Values)> AllTables()
    {
        List<(string Name, uint[] Values)> tables = new(256);
        tables.Add(("re_properties.name", ToValues(PropertiesName)));
        tables.Add(("re_properties.id", ToValues(PropertiesId)));
        tables.Add(("re_properties.value_set", ToValues(PropertiesValueSet)));
        tables.Add(("re_property_values.name", ToValues(PropertyValuesName)));
        tables.Add(("re_property_values.value_set", ToValues(PropertyValuesValueSet)));
        tables.Add(("re_property_values.id", ToValues(PropertyValuesId)));
        tables.Add(("re_expand_on_folding", ToValues(ExpandOnFolding)));
        tables.Add(("re_alphabetic_table_1", ToValues(AlphabeticTable1)));
        tables.Add(("re_alphabetic_table_2", ToValues(AlphabeticTable2)));
        tables.Add(("re_alphabetic_table_3", ToValues(AlphabeticTable3)));
        tables.Add(("re_alphanumeric_table_1", ToValues(AlphanumericTable1)));
        tables.Add(("re_alphanumeric_table_2", ToValues(AlphanumericTable2)));
        tables.Add(("re_alphanumeric_table_3", ToValues(AlphanumericTable3)));
        tables.Add(("re_bidi_class_table_1", ToValues(BidiClassTable1)));
        tables.Add(("re_bidi_class_table_2", ToValues(BidiClassTable2)));
        tables.Add(("re_bidi_class_table_3", ToValues(BidiClassTable3)));
        tables.Add(("re_bidi_mirrored_table_1", ToValues(BidiMirroredTable1)));
        tables.Add(("re_bidi_mirrored_table_2", ToValues(BidiMirroredTable2)));
        tables.Add(("re_bidi_mirrored_table_3", ToValues(BidiMirroredTable3)));
        tables.Add(("re_block_table_1", ToValues(BlockTable1)));
        tables.Add(("re_block_table_2", ToValues(BlockTable2)));
        tables.Add(("re_block_table_3", ToValues(BlockTable3)));
        tables.Add(("re_canonical_combining_class_table_1", ToValues(CanonicalCombiningClassTable1)));
        tables.Add(("re_canonical_combining_class_table_2", ToValues(CanonicalCombiningClassTable2)));
        tables.Add(("re_canonical_combining_class_table_3", ToValues(CanonicalCombiningClassTable3)));
        tables.Add(("re_cased_table_1", ToValues(CasedTable1)));
        tables.Add(("re_cased_table_2", ToValues(CasedTable2)));
        tables.Add(("re_cased_table_3", ToValues(CasedTable3)));
        tables.Add(("re_case_ignorable_table_1", ToValues(CaseIgnorableTable1)));
        tables.Add(("re_case_ignorable_table_2", ToValues(CaseIgnorableTable2)));
        tables.Add(("re_case_ignorable_table_3", ToValues(CaseIgnorableTable3)));
        tables.Add(("re_changes_when_casefolded_table_1", ToValues(ChangesWhenCasefoldedTable1)));
        tables.Add(("re_changes_when_casefolded_table_2", ToValues(ChangesWhenCasefoldedTable2)));
        tables.Add(("re_changes_when_casefolded_table_3", ToValues(ChangesWhenCasefoldedTable3)));
        tables.Add(("re_changes_when_casemapped_table_1", ToValues(ChangesWhenCasemappedTable1)));
        tables.Add(("re_changes_when_casemapped_table_2", ToValues(ChangesWhenCasemappedTable2)));
        tables.Add(("re_changes_when_casemapped_table_3", ToValues(ChangesWhenCasemappedTable3)));
        tables.Add(("re_changes_when_lowercased_table_1", ToValues(ChangesWhenLowercasedTable1)));
        tables.Add(("re_changes_when_lowercased_table_2", ToValues(ChangesWhenLowercasedTable2)));
        tables.Add(("re_changes_when_lowercased_table_3", ToValues(ChangesWhenLowercasedTable3)));
        tables.Add(("re_changes_when_titlecased_table_1", ToValues(ChangesWhenTitlecasedTable1)));
        tables.Add(("re_changes_when_titlecased_table_2", ToValues(ChangesWhenTitlecasedTable2)));
        tables.Add(("re_changes_when_titlecased_table_3", ToValues(ChangesWhenTitlecasedTable3)));
        tables.Add(("re_changes_when_uppercased_table_1", ToValues(ChangesWhenUppercasedTable1)));
        tables.Add(("re_changes_when_uppercased_table_2", ToValues(ChangesWhenUppercasedTable2)));
        tables.Add(("re_changes_when_uppercased_table_3", ToValues(ChangesWhenUppercasedTable3)));
        tables.Add(("re_dash_table_1", ToValues(DashTable1)));
        tables.Add(("re_dash_table_2", ToValues(DashTable2)));
        tables.Add(("re_dash_table_3", ToValues(DashTable3)));
        tables.Add(("re_decomposition_type_table_1", ToValues(DecompositionTypeTable1)));
        tables.Add(("re_decomposition_type_table_2", ToValues(DecompositionTypeTable2)));
        tables.Add(("re_decomposition_type_table_3", ToValues(DecompositionTypeTable3)));
        tables.Add(("re_default_ignorable_code_point_table_1", ToValues(DefaultIgnorableCodePointTable1)));
        tables.Add(("re_default_ignorable_code_point_table_2", ToValues(DefaultIgnorableCodePointTable2)));
        tables.Add(("re_default_ignorable_code_point_table_3", ToValues(DefaultIgnorableCodePointTable3)));
        tables.Add(("re_diacritic_table_1", ToValues(DiacriticTable1)));
        tables.Add(("re_diacritic_table_2", ToValues(DiacriticTable2)));
        tables.Add(("re_diacritic_table_3", ToValues(DiacriticTable3)));
        tables.Add(("re_east_asian_width_table_1", ToValues(EastAsianWidthTable1)));
        tables.Add(("re_east_asian_width_table_2", ToValues(EastAsianWidthTable2)));
        tables.Add(("re_east_asian_width_table_3", ToValues(EastAsianWidthTable3)));
        tables.Add(("re_emoji_table_1", ToValues(EmojiTable1)));
        tables.Add(("re_emoji_table_2", ToValues(EmojiTable2)));
        tables.Add(("re_emoji_table_3", ToValues(EmojiTable3)));
        tables.Add(("re_emoji_component_table_1", ToValues(EmojiComponentTable1)));
        tables.Add(("re_emoji_component_table_2", ToValues(EmojiComponentTable2)));
        tables.Add(("re_emoji_component_table_3", ToValues(EmojiComponentTable3)));
        tables.Add(("re_emoji_modifier_base_table_1", ToValues(EmojiModifierBaseTable1)));
        tables.Add(("re_emoji_modifier_base_table_2", ToValues(EmojiModifierBaseTable2)));
        tables.Add(("re_emoji_modifier_base_table_3", ToValues(EmojiModifierBaseTable3)));
        tables.Add(("re_emoji_presentation_table_1", ToValues(EmojiPresentationTable1)));
        tables.Add(("re_emoji_presentation_table_2", ToValues(EmojiPresentationTable2)));
        tables.Add(("re_emoji_presentation_table_3", ToValues(EmojiPresentationTable3)));
        tables.Add(("re_extended_pictographic_table_1", ToValues(ExtendedPictographicTable1)));
        tables.Add(("re_extended_pictographic_table_2", ToValues(ExtendedPictographicTable2)));
        tables.Add(("re_extended_pictographic_table_3", ToValues(ExtendedPictographicTable3)));
        tables.Add(("re_extender_table_1", ToValues(ExtenderTable1)));
        tables.Add(("re_extender_table_2", ToValues(ExtenderTable2)));
        tables.Add(("re_extender_table_3", ToValues(ExtenderTable3)));
        tables.Add(("re_general_category_table_1", ToValues(GeneralCategoryTable1)));
        tables.Add(("re_general_category_table_2", ToValues(GeneralCategoryTable2)));
        tables.Add(("re_general_category_table_3", ToValues(GeneralCategoryTable3)));
        tables.Add(("re_graph_table_1", ToValues(GraphTable1)));
        tables.Add(("re_graph_table_2", ToValues(GraphTable2)));
        tables.Add(("re_graph_table_3", ToValues(GraphTable3)));
        tables.Add(("re_grapheme_base_table_1", ToValues(GraphemeBaseTable1)));
        tables.Add(("re_grapheme_base_table_2", ToValues(GraphemeBaseTable2)));
        tables.Add(("re_grapheme_base_table_3", ToValues(GraphemeBaseTable3)));
        tables.Add(("re_grapheme_cluster_break_table_1", ToValues(GraphemeClusterBreakTable1)));
        tables.Add(("re_grapheme_cluster_break_table_2", ToValues(GraphemeClusterBreakTable2)));
        tables.Add(("re_grapheme_cluster_break_table_3", ToValues(GraphemeClusterBreakTable3)));
        tables.Add(("re_grapheme_extend_table_1", ToValues(GraphemeExtendTable1)));
        tables.Add(("re_grapheme_extend_table_2", ToValues(GraphemeExtendTable2)));
        tables.Add(("re_grapheme_extend_table_3", ToValues(GraphemeExtendTable3)));
        tables.Add(("re_grapheme_link_table_1", ToValues(GraphemeLinkTable1)));
        tables.Add(("re_grapheme_link_table_2", ToValues(GraphemeLinkTable2)));
        tables.Add(("re_grapheme_link_table_3", ToValues(GraphemeLinkTable3)));
        tables.Add(("re_hangul_syllable_type_table_1", ToValues(HangulSyllableTypeTable1)));
        tables.Add(("re_hangul_syllable_type_table_2", ToValues(HangulSyllableTypeTable2)));
        tables.Add(("re_hangul_syllable_type_table_3", ToValues(HangulSyllableTypeTable3)));
        tables.Add(("re_horiz_space_table_1", ToValues(HorizSpaceTable1)));
        tables.Add(("re_horiz_space_table_2", ToValues(HorizSpaceTable2)));
        tables.Add(("re_horiz_space_table_3", ToValues(HorizSpaceTable3)));
        tables.Add(("re_hyphen_table_1", ToValues(HyphenTable1)));
        tables.Add(("re_hyphen_table_2", ToValues(HyphenTable2)));
        tables.Add(("re_hyphen_table_3", ToValues(HyphenTable3)));
        tables.Add(("re_id_compat_math_continue_table_1", ToValues(IdCompatMathContinueTable1)));
        tables.Add(("re_id_compat_math_continue_table_2", ToValues(IdCompatMathContinueTable2)));
        tables.Add(("re_id_compat_math_continue_table_3", ToValues(IdCompatMathContinueTable3)));
        tables.Add(("re_id_compat_math_start_table_1", ToValues(IdCompatMathStartTable1)));
        tables.Add(("re_id_compat_math_start_table_2", ToValues(IdCompatMathStartTable2)));
        tables.Add(("re_id_compat_math_start_table_3", ToValues(IdCompatMathStartTable3)));
        tables.Add(("re_id_continue_table_1", ToValues(IdContinueTable1)));
        tables.Add(("re_id_continue_table_2", ToValues(IdContinueTable2)));
        tables.Add(("re_id_continue_table_3", ToValues(IdContinueTable3)));
        tables.Add(("re_ideographic_table_1", ToValues(IdeographicTable1)));
        tables.Add(("re_ideographic_table_2", ToValues(IdeographicTable2)));
        tables.Add(("re_ideographic_table_3", ToValues(IdeographicTable3)));
        tables.Add(("re_id_start_table_1", ToValues(IdStartTable1)));
        tables.Add(("re_id_start_table_2", ToValues(IdStartTable2)));
        tables.Add(("re_id_start_table_3", ToValues(IdStartTable3)));
        tables.Add(("re_indic_conjunct_break_table_1", ToValues(IndicConjunctBreakTable1)));
        tables.Add(("re_indic_conjunct_break_table_2", ToValues(IndicConjunctBreakTable2)));
        tables.Add(("re_indic_conjunct_break_table_3", ToValues(IndicConjunctBreakTable3)));
        tables.Add(("re_indic_positional_category_table_1", ToValues(IndicPositionalCategoryTable1)));
        tables.Add(("re_indic_positional_category_table_2", ToValues(IndicPositionalCategoryTable2)));
        tables.Add(("re_indic_positional_category_table_3", ToValues(IndicPositionalCategoryTable3)));
        tables.Add(("re_indic_syllabic_category_table_1", ToValues(IndicSyllabicCategoryTable1)));
        tables.Add(("re_indic_syllabic_category_table_2", ToValues(IndicSyllabicCategoryTable2)));
        tables.Add(("re_indic_syllabic_category_table_3", ToValues(IndicSyllabicCategoryTable3)));
        tables.Add(("re_joining_group_table_1", ToValues(JoiningGroupTable1)));
        tables.Add(("re_joining_group_table_2", ToValues(JoiningGroupTable2)));
        tables.Add(("re_joining_group_table_3", ToValues(JoiningGroupTable3)));
        tables.Add(("re_joining_type_table_1", ToValues(JoiningTypeTable1)));
        tables.Add(("re_joining_type_table_2", ToValues(JoiningTypeTable2)));
        tables.Add(("re_joining_type_table_3", ToValues(JoiningTypeTable3)));
        tables.Add(("re_line_break_table_1", ToValues(LineBreakTable1)));
        tables.Add(("re_line_break_table_2", ToValues(LineBreakTable2)));
        tables.Add(("re_line_break_table_3", ToValues(LineBreakTable3)));
        tables.Add(("re_lowercase_table_1", ToValues(LowercaseTable1)));
        tables.Add(("re_lowercase_table_2", ToValues(LowercaseTable2)));
        tables.Add(("re_lowercase_table_3", ToValues(LowercaseTable3)));
        tables.Add(("re_math_table_1", ToValues(MathTable1)));
        tables.Add(("re_math_table_2", ToValues(MathTable2)));
        tables.Add(("re_math_table_3", ToValues(MathTable3)));
        tables.Add(("re_modifier_combining_mark_table_1", ToValues(ModifierCombiningMarkTable1)));
        tables.Add(("re_modifier_combining_mark_table_2", ToValues(ModifierCombiningMarkTable2)));
        tables.Add(("re_modifier_combining_mark_table_3", ToValues(ModifierCombiningMarkTable3)));
        tables.Add(("re_nfc_quick_check_table_1", ToValues(NfcQuickCheckTable1)));
        tables.Add(("re_nfc_quick_check_table_2", ToValues(NfcQuickCheckTable2)));
        tables.Add(("re_nfc_quick_check_table_3", ToValues(NfcQuickCheckTable3)));
        tables.Add(("re_nfd_quick_check_table_1", ToValues(NfdQuickCheckTable1)));
        tables.Add(("re_nfd_quick_check_table_2", ToValues(NfdQuickCheckTable2)));
        tables.Add(("re_nfd_quick_check_table_3", ToValues(NfdQuickCheckTable3)));
        tables.Add(("re_nfkc_quick_check_table_1", ToValues(NfkcQuickCheckTable1)));
        tables.Add(("re_nfkc_quick_check_table_2", ToValues(NfkcQuickCheckTable2)));
        tables.Add(("re_nfkc_quick_check_table_3", ToValues(NfkcQuickCheckTable3)));
        tables.Add(("re_nfkd_quick_check_table_1", ToValues(NfkdQuickCheckTable1)));
        tables.Add(("re_nfkd_quick_check_table_2", ToValues(NfkdQuickCheckTable2)));
        tables.Add(("re_nfkd_quick_check_table_3", ToValues(NfkdQuickCheckTable3)));
        tables.Add(("re_noncharacter_code_point_table_1", ToValues(NoncharacterCodePointTable1)));
        tables.Add(("re_noncharacter_code_point_table_2", ToValues(NoncharacterCodePointTable2)));
        tables.Add(("re_noncharacter_code_point_table_3", ToValues(NoncharacterCodePointTable3)));
        tables.Add(("re_numeric_type_table_1", ToValues(NumericTypeTable1)));
        tables.Add(("re_numeric_type_table_2", ToValues(NumericTypeTable2)));
        tables.Add(("re_numeric_type_table_3", ToValues(NumericTypeTable3)));
        tables.Add(("re_numeric_value_table_1", ToValues(NumericValueTable1)));
        tables.Add(("re_numeric_value_table_2", ToValues(NumericValueTable2)));
        tables.Add(("re_numeric_value_table_3", ToValues(NumericValueTable3)));
        tables.Add(("re_other_alphabetic_table_1", ToValues(OtherAlphabeticTable1)));
        tables.Add(("re_other_alphabetic_table_2", ToValues(OtherAlphabeticTable2)));
        tables.Add(("re_other_alphabetic_table_3", ToValues(OtherAlphabeticTable3)));
        tables.Add(("re_other_default_ignorable_code_point_table_1", ToValues(OtherDefaultIgnorableCodePointTable1)));
        tables.Add(("re_other_default_ignorable_code_point_table_2", ToValues(OtherDefaultIgnorableCodePointTable2)));
        tables.Add(("re_other_default_ignorable_code_point_table_3", ToValues(OtherDefaultIgnorableCodePointTable3)));
        tables.Add(("re_other_grapheme_extend_table_1", ToValues(OtherGraphemeExtendTable1)));
        tables.Add(("re_other_grapheme_extend_table_2", ToValues(OtherGraphemeExtendTable2)));
        tables.Add(("re_other_grapheme_extend_table_3", ToValues(OtherGraphemeExtendTable3)));
        tables.Add(("re_other_lowercase_table_1", ToValues(OtherLowercaseTable1)));
        tables.Add(("re_other_lowercase_table_2", ToValues(OtherLowercaseTable2)));
        tables.Add(("re_other_lowercase_table_3", ToValues(OtherLowercaseTable3)));
        tables.Add(("re_other_math_table_1", ToValues(OtherMathTable1)));
        tables.Add(("re_other_math_table_2", ToValues(OtherMathTable2)));
        tables.Add(("re_other_math_table_3", ToValues(OtherMathTable3)));
        tables.Add(("re_pattern_syntax_table_1", ToValues(PatternSyntaxTable1)));
        tables.Add(("re_pattern_syntax_table_2", ToValues(PatternSyntaxTable2)));
        tables.Add(("re_pattern_syntax_table_3", ToValues(PatternSyntaxTable3)));
        tables.Add(("re_posix_alnum_table_1", ToValues(PosixAlnumTable1)));
        tables.Add(("re_posix_alnum_table_2", ToValues(PosixAlnumTable2)));
        tables.Add(("re_posix_alnum_table_3", ToValues(PosixAlnumTable3)));
        tables.Add(("re_posix_punct_table_1", ToValues(PosixPunctTable1)));
        tables.Add(("re_posix_punct_table_2", ToValues(PosixPunctTable2)));
        tables.Add(("re_posix_punct_table_3", ToValues(PosixPunctTable3)));
        tables.Add(("re_print_table_1", ToValues(PrintTable1)));
        tables.Add(("re_print_table_2", ToValues(PrintTable2)));
        tables.Add(("re_print_table_3", ToValues(PrintTable3)));
        tables.Add(("re_quotation_mark_table_1", ToValues(QuotationMarkTable1)));
        tables.Add(("re_quotation_mark_table_2", ToValues(QuotationMarkTable2)));
        tables.Add(("re_quotation_mark_table_3", ToValues(QuotationMarkTable3)));
        tables.Add(("re_script_table_1", ToValues(ScriptTable1)));
        tables.Add(("re_script_table_2", ToValues(ScriptTable2)));
        tables.Add(("re_script_table_3", ToValues(ScriptTable3)));
        tables.Add(("script_extensions_table_1", ToValues(ScriptExtensionsTable1)));
        tables.Add(("script_extensions_table_2", ToValues(ScriptExtensionsTable2)));
        tables.Add(("script_extensions_table_3", ToValues(ScriptExtensionsTable3)));
        tables.Add(("script_extensions_table_4", ToValues(ScriptExtensionsTable4)));
        tables.Add(("script_extensions_table_5", ToValues(ScriptExtensionsTable5)));
        tables.Add(("re_sentence_break_table_1", ToValues(SentenceBreakTable1)));
        tables.Add(("re_sentence_break_table_2", ToValues(SentenceBreakTable2)));
        tables.Add(("re_sentence_break_table_3", ToValues(SentenceBreakTable3)));
        tables.Add(("re_sentence_terminal_table_1", ToValues(SentenceTerminalTable1)));
        tables.Add(("re_sentence_terminal_table_2", ToValues(SentenceTerminalTable2)));
        tables.Add(("re_sentence_terminal_table_3", ToValues(SentenceTerminalTable3)));
        tables.Add(("re_soft_dotted_table_1", ToValues(SoftDottedTable1)));
        tables.Add(("re_soft_dotted_table_2", ToValues(SoftDottedTable2)));
        tables.Add(("re_soft_dotted_table_3", ToValues(SoftDottedTable3)));
        tables.Add(("re_terminal_punctuation_table_1", ToValues(TerminalPunctuationTable1)));
        tables.Add(("re_terminal_punctuation_table_2", ToValues(TerminalPunctuationTable2)));
        tables.Add(("re_terminal_punctuation_table_3", ToValues(TerminalPunctuationTable3)));
        tables.Add(("re_unified_ideograph_table_1", ToValues(UnifiedIdeographTable1)));
        tables.Add(("re_unified_ideograph_table_2", ToValues(UnifiedIdeographTable2)));
        tables.Add(("re_unified_ideograph_table_3", ToValues(UnifiedIdeographTable3)));
        tables.Add(("re_uppercase_table_1", ToValues(UppercaseTable1)));
        tables.Add(("re_uppercase_table_2", ToValues(UppercaseTable2)));
        tables.Add(("re_uppercase_table_3", ToValues(UppercaseTable3)));
        tables.Add(("re_white_space_table_1", ToValues(WhiteSpaceTable1)));
        tables.Add(("re_white_space_table_2", ToValues(WhiteSpaceTable2)));
        tables.Add(("re_white_space_table_3", ToValues(WhiteSpaceTable3)));
        tables.Add(("re_word_table_1", ToValues(WordTable1)));
        tables.Add(("re_word_table_2", ToValues(WordTable2)));
        tables.Add(("re_word_table_3", ToValues(WordTable3)));
        tables.Add(("re_word_break_table_1", ToValues(WordBreakTable1)));
        tables.Add(("re_word_break_table_2", ToValues(WordBreakTable2)));
        tables.Add(("re_word_break_table_3", ToValues(WordBreakTable3)));
        tables.Add(("re_xdigit_table_1", ToValues(XdigitTable1)));
        tables.Add(("re_xdigit_table_2", ToValues(XdigitTable2)));
        tables.Add(("re_xdigit_table_3", ToValues(XdigitTable3)));
        tables.Add(("re_xid_continue_table_1", ToValues(XidContinueTable1)));
        tables.Add(("re_xid_continue_table_2", ToValues(XidContinueTable2)));
        tables.Add(("re_xid_continue_table_3", ToValues(XidContinueTable3)));
        tables.Add(("re_xid_start_table_1", ToValues(XidStartTable1)));
        tables.Add(("re_xid_start_table_2", ToValues(XidStartTable2)));
        tables.Add(("re_xid_start_table_3", ToValues(XidStartTable3)));
        tables.Add(("re_all_cases_table_1", ToValues(AllCasesTable1)));
        tables.Add(("re_all_cases_table_2", ToValues(AllCasesTable2)));
        tables.Add(("re_all_cases_table_3", ToValues(AllCasesTable3)));
        tables.Add(("re_all_cases_table_4.delta", ToValues(AllCasesTable4Delta)));
        tables.Add(("re_all_cases_table_4.others", ToValues(AllCasesTable4Others)));
        tables.Add(("re_simple_folding_table_1", ToValues(SimpleFoldingTable1)));
        tables.Add(("re_simple_folding_table_2", ToValues(SimpleFoldingTable2)));
        tables.Add(("re_simple_folding_table_3", ToValues(SimpleFoldingTable3)));
        tables.Add(("re_simple_folding_table_4", ToValues(SimpleFoldingTable4)));
        tables.Add(("re_full_folding_table_1", ToValues(FullFoldingTable1)));
        tables.Add(("re_full_folding_table_2", ToValues(FullFoldingTable2)));
        tables.Add(("re_full_folding_table_3", ToValues(FullFoldingTable3)));
        tables.Add(("re_full_folding_table_4.data", ToValues(FullFoldingTable4Data)));
        return tables;
    }

    private static uint[] ToValues(ReadOnlySpan<byte> table)
    {
        uint[] values = new uint[table.Length];
        for (int i = 0; i < table.Length; i++)
        {
            values[i] = table[i];
        }

        return values;
    }

    private static uint[] ToValues(ushort[] table)
    {
        uint[] values = new uint[table.Length];
        for (int i = 0; i < table.Length; i++)
        {
            values[i] = table[i];
        }

        return values;
    }

    private static uint[] ToValues(byte[] table)
    {
        uint[] values = new uint[table.Length];
        for (int i = 0; i < table.Length; i++)
        {
            values[i] = table[i];
        }

        return values;
    }

    private static uint[] ToValues(uint[] table) => (uint[])table.Clone();
}
