#!/usr/bin/env python3
"""Record the oracle fixtures for the transliterated Unicode tables.

Three fixtures, each a digest rather than a million rows:

1. **Tables.** A length and a SHA-256 for every table in ``upstream/src/_regex_unicode.c``,
   taken by a deliberately naive second parse of that file - a flat sweep for
   ``name[] = { ... };`` with no consumption tracking, nothing shared with
   ``tools/transliterate-unicode.py``. A test walks ``UnicodeTables.AllTables()`` and requires
   the same numbers, so a bug in the transliterator shows up as a mismatch rather than as
   plausible-looking wrong data.

2. **Casing.** ``get_all_cases`` and ``fold_case`` over every codepoint from 0 to 0x10FFFF, for
   each encoding and case-folding combination, each folded into one SHA-256 per side. Narrow a
   mismatch by plane and then by block in a throwaway script.

3. **Properties.** The whole ``get_properties`` dictionary - 185 properties and 1,704 values,
   munged names and ids - plus ``has_property_value`` over every property/value pair against a
   fixed spread of codepoints.

Fixtures 2 and 3 call the installed ``regex`` C extension directly. Fixture 1 needs only the
pinned submodule. ``--check`` regenerates and diffs, which is what the oracle CI job runs.

Usage:
    python tools/record-unicode-fixtures.py
    python tools/record-unicode-fixtures.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
C_PATH = REPO_ROOT / 'upstream/src/_regex_unicode.c'
FIXTURE_PATH = REPO_ROOT / 'tests/FuzzyRegex.Tests/Gaps/Unicode/unicode-fixtures.json'
# Written by tools/build-character-names.py; read here for the Unicode 17.0 additions, which the
# host's older unicodedata cannot answer for. Run that script first.
CHARACTER_NAMES_PATH = REPO_ROOT / 'tests/FuzzyRegex.Tests/Gaps/Unicode/character-names.json'

MAX_CODEPOINT = 0x10FFFF

FIXTURE_COMMENT = (
    'GENERATED by tools/record-unicode-fixtures.py. Do not edit by hand. '
    'Digests of upstream\'s Unicode tables and of the C extension\'s casing and property answers.'
)

# The struct arrays, and how the transliterator flattens each one: field name, then how many
# slots the C declaration gives that field (C zero-fills the rest of a partly initialised
# aggregate, and the flattened array has to agree).
STRUCT_TABLES = {
    're_properties': [('name', 1), ('id', 1), ('value_set', 1)],
    're_property_values': [('name', 1), ('value_set', 1), ('id', 1)],
    're_all_cases_table_4': [('delta', 1), ('others', 3)],
    're_full_folding_table_4': [('data', 3)],
}


def digest(values) -> str:
    """The digest a C# test can reproduce: the decimal values, comma separated, as UTF-8."""
    return hashlib.sha256(','.join(str(v) for v in values).encode('utf-8')).hexdigest()


# --------------------------------------------------------------------------------------
# Fixture 1: the tables, parsed naively straight out of the C
# --------------------------------------------------------------------------------------

def naive_table_digests() -> dict[str, dict]:
    """A flat sweep of the C file for array definitions. Deliberately dumb and standalone."""
    source = C_PATH.read_text(encoding='utf-8')
    tables: dict[str, dict] = {}

    for match in re.finditer(r'(\w+)\s+(\w+)\[\]\s*=\s*\{(.*?)\n\};', source, re.S):
        type_name, name, body = match.group(1), match.group(2), match.group(3)
        if type_name == 'char*' or name in ('re_strings', 're_get_property'):
            continue
        body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)

        if name in STRUCT_TABLES:
            rows = [row for row in
                    (r.strip().rstrip(',') for r in body.split('\n')) if row]
            columns: list[list[int]] = [[] for _ in STRUCT_TABLES[name]]
            for row in rows:
                # `{ 1, { 454, 0}}` and `{{64357, 102, 105}}`: split the outer braces into cells,
                # each of which is either one number or a braced list.
                cells = [c for c in re.findall(r'\{[^{}]*\}|[^,{}]+', row[1:-1]) if c.strip()]
                if len(cells) != len(columns):
                    raise SystemExit(f'{name}: row {row!r} has {len(cells)} cells')
                for i, (cell, (_, arity)) in enumerate(zip(cells, STRUCT_TABLES[name])):
                    numbers = [int(n) for n in re.findall(r'-?\d+', cell)]
                    if len(numbers) > arity:
                        raise SystemExit(f'{name}: cell {cell!r} has more than {arity} values')
                    columns[i].extend(numbers + [0] * (arity - len(numbers)))
            for (field, _), values in zip(STRUCT_TABLES[name], columns):
                tables[f'{name}.{field}'] = {'length': len(values), 'sha256': digest(values)}
            continue

        values = [int(n) for n in re.findall(r'-?\d+', body)]
        tables[name] = {'length': len(values), 'sha256': digest(values)}

    if not tables:
        raise SystemExit('the naive parse found no tables at all')
    return tables


# --------------------------------------------------------------------------------------
# Fixture 2: casing, exhaustive over every codepoint
# --------------------------------------------------------------------------------------

def casing_digests(regex, _regex) -> dict[str, str]:
    # Upstream's own flag names, so the labels say what was asked for.
    encodings = {'unicode': regex.UNICODE, 'ascii': regex.ASCII}
    foldings = {'simple': regex.IGNORECASE, 'full': regex.IGNORECASE | regex.FULLCASE}

    result: dict[str, str] = {}
    for encoding_name, encoding in encodings.items():
        for folding_name, folding in foldings.items():
            flags = encoding | folding

            all_cases = hashlib.sha256()
            fold = hashlib.sha256()
            for codepoint in range(MAX_CODEPOINT + 1):
                cases = _regex.get_all_cases(flags, codepoint)
                all_cases.update(
                    f'{codepoint}:'
                    f'{",".join("" if c is None else str(c) for c in cases)}\n'.encode('utf-8'))

                folded = _regex.fold_case(flags, chr(codepoint))
                fold.update(
                    f'{codepoint}:{",".join(str(ord(c)) for c in folded)}\n'.encode('utf-8'))

            result[f'get_all_cases.{encoding_name}.{folding_name}'] = all_cases.hexdigest()
            result[f'fold_case.{encoding_name}.{folding_name}'] = fold.hexdigest()

    # fold_case with IGNORECASE off returns the string unchanged whatever else is set.
    unchanged = hashlib.sha256()
    for codepoint in range(MAX_CODEPOINT + 1):
        folded = _regex.fold_case(regex.UNICODE | regex.FULLCASE, chr(codepoint))
        unchanged.update(
            f'{codepoint}:{",".join(str(ord(c)) for c in folded)}\n'.encode('utf-8'))
    result['fold_case.unicode.none'] = unchanged.hexdigest()

    return result


# --------------------------------------------------------------------------------------
# Fixture 3: the property dictionary and has_property_value
# --------------------------------------------------------------------------------------

def property_sample_codepoints() -> list[int]:
    """Dense over Latin-1 and the combining marks, then a prime stride over everything else."""
    return list(range(0, 0x200)) + list(range(0x200, MAX_CODEPOINT + 1, 1021))


def property_digests(_regex) -> dict:
    properties = _regex.get_properties()

    canonical = hashlib.sha256()
    pairs: list[tuple[str, str, int]] = []
    for property_name in sorted(properties):
        property_id, values = properties[property_name]
        canonical.update(f'{property_name}={property_id}:'.encode('utf-8'))
        canonical.update(
            ','.join(f'{v}={values[v]}' for v in sorted(values)).encode('utf-8'))
        canonical.update(b'\n')
        for value_name in sorted(values):
            pairs.append((property_name, value_name, (property_id << 16) | values[value_name]))

    codepoints = property_sample_codepoints()
    answers = hashlib.sha256()
    for property_name, value_name, code in pairs:
        for codepoint in codepoints:
            answers.update(
                f'{code}:{codepoint}:'
                f'{_regex.has_property_value(code, codepoint)}\n'.encode('utf-8'))

    return {
        'propertyCount': len(properties),
        'propertyValuePairCount': len(pairs),
        'properties': canonical.hexdigest(),
        'hasPropertyValueCodepoints': codepoints,
        'hasPropertyValue': answers.hexdigest(),
    }


# --------------------------------------------------------------------------------------
# Fixture 4: the Python str predicates the parser leans on
# --------------------------------------------------------------------------------------

def python_str_digest(_regex) -> dict:
    """``str.isalpha``, ``str.isdigit`` and ``str.isidentifier``, for every codepoint.

    These are CPython's, not upstream's, and CPython answers them from its own copy of the UCD -
    16.0.0 on the recording host, against upstream's 17.0.0 tables. The 4,803 codepoints Unicode
    17.0 added are therefore skipped: the host has no answer for them. Everything else is
    compared, so the mapping the port relies on is measured rather than assumed.
    """
    names = json.loads(CHARACTER_NAMES_PATH.read_text(encoding='utf-8'))
    new_in_17 = set()
    for first, last in names['codepointRangesAddedIn17']:
        new_in_17.update(range(first, last + 1))

    properties = _regex.get_properties()

    def code(property_name: str, value_name: str) -> int:
        property_id, values = properties[property_name]
        return (property_id << 16) | values[value_name]

    letter = code('GENERALCATEGORY', 'L')
    decimal = code('NUMERICTYPE', 'DECIMAL')
    digit = code('NUMERICTYPE', 'DIGIT')
    xid_start = code('XIDSTART', 'Y')
    xid_continue = code('XIDCONTINUE', 'Y')

    answers = hashlib.sha256()
    counted = 0
    for codepoint in range(MAX_CODEPOINT + 1):
        if codepoint in new_in_17:
            continue
        character = chr(codepoint)

        is_alpha = character.isalpha()
        is_digit = character.isdigit()
        # isidentifier() on one character is the "may start" test; on 'a' + it, the "may
        # continue" test.
        is_start = character.isidentifier()
        is_continue = ('a' + character).isidentifier()

        if (is_alpha != bool(_regex.has_property_value(letter, codepoint))
                or is_digit != (bool(_regex.has_property_value(decimal, codepoint))
                                or bool(_regex.has_property_value(digit, codepoint)))
                or is_start != (bool(_regex.has_property_value(xid_start, codepoint))
                                or character == '_')
                or is_continue != bool(_regex.has_property_value(xid_continue, codepoint))):
            raise SystemExit(
                f'U+{codepoint:04X}: CPython\'s str predicates and upstream\'s tables disagree. '
                f'src/FuzzyRegex/Unicode/PythonStr.cs records that they never do; find out what '
                f'changed before shipping.')

        answers.update(f'{codepoint}:{int(is_alpha)}{int(is_digit)}'
                       f'{int(is_start)}{int(is_continue)}\n'.encode('utf-8'))
        counted += 1

    return {
        'pythonStrCodepointCount': counted,
        'pythonStrSkippedNewIn17': len(new_in_17),
        'pythonStr': answers.hexdigest(),
    }


# --------------------------------------------------------------------------------------

def upstream_commit() -> str:
    return subprocess.run(
        ['git', '-C', str(REPO_ROOT / 'upstream'), 'rev-parse', 'HEAD'],
        capture_output=True, text=True, check=True,
    ).stdout.strip()


def build() -> dict:
    import regex
    import regex._regex as _regex
    import unicodedata

    unicode_version = re.search(r'#define RE_UNICODE_VERSION "(.+)"',
                                (REPO_ROOT / 'upstream/src/_regex_unicode.h')
                                .read_text(encoding='utf-8')).group(1)

    print('tables...', file=sys.stderr, flush=True)
    tables = naive_table_digests()
    print(f'  {len(tables)} tables', file=sys.stderr, flush=True)

    print('casing (1.1M codepoints x 5 combinations)...', file=sys.stderr, flush=True)
    casing = casing_digests(regex, _regex)

    print('properties...', file=sys.stderr, flush=True)
    properties = property_digests(_regex)

    print('python str predicates...', file=sys.stderr, flush=True)
    python_str = python_str_digest(_regex)

    return {
        'comment': FIXTURE_COMMENT,
        'regexVersion': regex.__version__,
        'upstreamCommit': upstream_commit(),
        'unicodeVersion': unicode_version,
        'pythonUnicodeVersion': unicodedata.unidata_version,
        'tables': tables,
        'casing': casing,
        **properties,
        **python_str,
    }


def render(fixture: dict) -> str:
    # One line per table and per digest, so a drifting table names itself in the diff. The
    # codepoint list is the one long line; it is data, not something a reader diffs.
    return json.dumps(fixture, indent=2, ensure_ascii=True, sort_keys=False) + '\n'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true',
                        help='regenerate and fail if the committed fixture differs')
    args = parser.parse_args()

    text = render(build())

    if args.check:
        existing = FIXTURE_PATH.read_text(encoding='utf-8') if FIXTURE_PATH.exists() else None
        if existing != text:
            print(f'record-unicode-fixtures: {FIXTURE_PATH} is out of date', file=sys.stderr)
            return 1
        print('record-unicode-fixtures: up to date')
        return 0

    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_text(text, encoding='utf-8', newline='\n')
    print(f'wrote {FIXTURE_PATH.relative_to(REPO_ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
