#!/usr/bin/env python3
"""Transliterate upstream's generated Unicode tables into C#.

Reads ``upstream/src/_regex_unicode.c`` and ``upstream/src/_regex_unicode.h`` - both of which
upstream generates from the UCD with ``tools/build_regex_unicode.py`` - and writes
``src/FuzzyRegex/Unicode/*.g.cs``.

We transliterate upstream's *output* rather than porting its generator, so the tables are
identical to upstream's by construction and no UCD download is needed. See
``docs/plan/2026-08-30-phase2-decisions.md`` decision A.

The script consumes the C source exhaustively: it walks a cursor over the file and every
byte must be matched by a known construct (a comment, a ``#define``, a typedef, a table or a
function). A shape it has never seen is a hard error, so a future upstream file cannot
silently drop a table.

Four functions are *not* transliterated - ``re_get_all_cases``, ``re_get_simple_case_folding``,
``re_get_full_case_folding`` and ``re_get_script_extensions``. They index struct arrays and
their C bodies do not fit the three-level-walk shape the other 100 share; they are hand-ported
in ``src/FuzzyRegex/Unicode/UnicodeCasing.cs``. Their C bodies are pinned here by exact text,
so an upstream change to any of them fails this script rather than passing silently.

Usage:
    python tools/transliterate-unicode.py            # write the files
    python tools/transliterate-unicode.py --check    # fail if the committed files differ
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
C_PATH = REPO / 'upstream/src/_regex_unicode.c'
H_PATH = REPO / 'upstream/src/_regex_unicode.h'
OUT_DIR = REPO / 'src/FuzzyRegex/Unicode'

NAMESPACE = 'Fuzzy.Text.RegularExpressions.Unicode'
CLASS = 'UnicodeTables'

HEADER = """// <auto-generated/>
// Transliterated from upstream/src/_regex_unicode.{ext} by tools/transliterate-unicode.py.
// Do not edit by hand: re-run the script instead.
#nullable enable

namespace {ns};

internal static partial class {cls}
{{
"""

FOOTER = '}\n'

# The four functions we hand-port, mapped to the SHA-256 of their whitespace-normalised C body.
# Hand-porting them keeps twenty single-use translation rules out of this script; pinning the
# body means an upstream change to one of them fails here rather than leaving UnicodeCasing.cs
# quietly stale. Re-pin only after reading the upstream diff and updating UnicodeCasing.cs.
HAND_PORTED = {
    'get_script_extensions': '2a5d6eabde079db1978ccfab3e2d8d348c6fd64f0529c54f06418331aec60ec9',
    'get_all_cases': '4591b155724ba2e8b3d3bbcf86df9056f362af3ff6fb0a6a7b7c7d7d6f5293be',
    'get_simple_case_folding': 'd44f1e16df10b15272418551545777b193fb19d0273eaa04823542aa40ab5678',
    'get_full_case_folding': '72066f2ca5b21dc3801d5df2016ba48d416524cbede84507df06c016da9e31ca',
}


def body_digest(body: str) -> str:
    return hashlib.sha256(' '.join(body.split()).encode('utf-8')).hexdigest()


# --------------------------------------------------------------------------------------
# Names
# --------------------------------------------------------------------------------------

def pascal(c_name: str) -> str:
    """``re_alphabetic_table_1`` -> ``AlphabeticTable1``; ``re_get_word`` -> ``GetWord``."""
    name = c_name[3:] if c_name.startswith('re_') else c_name
    return ''.join(part.capitalize() for part in name.split('_') if part)


def const_name(c_name: str) -> str:
    """``RE_PROP_GC`` -> ``PropGc``, ``RE_MAX_CASES`` -> ``MaxCases``."""
    name = c_name[3:] if c_name.startswith('RE_') else c_name
    return ''.join(part.capitalize() for part in name.split('_') if part)


# --------------------------------------------------------------------------------------
# Parsing the C source
# --------------------------------------------------------------------------------------

class Fail(Exception):
    pass


class Source:
    def __init__(self, text: str, path: Path):
        self.text = text
        self.path = path
        self.pos = 0

    def line_of(self, pos: int) -> int:
        return self.text.count('\n', 0, pos) + 1

    def fail(self, message: str) -> None:
        raise Fail(f'{self.path.name}:{self.line_of(self.pos)}: {message}\n'
                   f'  next: {self.text[self.pos:self.pos + 120]!r}')

    def skip_trivia(self) -> str | None:
        """Skip blank lines and block comments. Returns the last comment's text."""
        comment = None
        while self.pos < len(self.text):
            m = re.compile(r'[ \t\r\n]+').match(self.text, self.pos)
            if m:
                self.pos = m.end()
                continue
            m = re.compile(r'/\*(.*?)\*/', re.S).match(self.text, self.pos)
            if m:
                comment = ' '.join(m.group(1).split())
                self.pos = m.end()
                continue
            break
        return comment

    def try_match(self, pattern: str, flags: int = 0) -> re.Match | None:
        m = re.compile(pattern, flags).match(self.text, self.pos)
        if m:
            self.pos = m.end()
        return m


def parse_header(path: Path) -> tuple[list[tuple[str, str]], dict[str, int]]:
    """Returns the ``#define``s as (name, value) and the extern arrays as name -> length."""
    src = Source(path.read_text(encoding='utf-8'), path)
    defines: list[tuple[str, str]] = []
    externs: dict[str, int] = {}
    ignorable = (
        r'typedef\s+[^;{]+;',                       # scalar typedefs
        r'typedef\s+struct\s+\w+\s*\{[^}]*\}\s*\w+;',  # struct typedefs
        r'typedef\s+\w+\s*\(\*\w+\)\([^)]*\);',     # function-pointer typedef
        r'#if[^\n]*\n(?:[^\n]*\n)*?#endif\n',       # the FALSE/TRUE guard
        r'(?:RE_UINT32|int)\s+re_\w+\([^)]*\);',    # function declarations
    )
    while True:
        src.skip_trivia()
        if src.pos >= len(src.text):
            break
        m = src.try_match(r'#define\s+(\w+)\s+([^\n]*)\n')
        if m:
            defines.append((m.group(1), m.group(2).strip()))
            continue
        m = src.try_match(r'extern\s+[\w*]+\s+(\w+)\[(\d+)\];')
        if m:
            externs[m.group(1)] = int(m.group(2))
            continue
        if any(src.try_match(p) for p in ignorable):
            continue
        src.fail('unrecognised construct in the header')
    return defines, externs


def split_values(body: str) -> list[str]:
    return [v.strip() for v in body.split(',') if v.strip()]


def parse_source(path: Path):
    """Walks the C file, consuming every construct. Returns the pieces in file order."""
    src = Source(path.read_text(encoding='utf-8'), path)
    pieces: list[dict] = []

    src.skip_trivia()
    if not src.try_match(r'#include\s+"_regex_unicode\.h"\n'):
        src.fail('expected the header include first')

    while True:
        comment = src.skip_trivia()
        if src.pos >= len(src.text):
            break

        m = src.try_match(r'#define\s+(\w+)\s+([^\n]*)\n')
        if m:
            pieces.append({'kind': 'define', 'name': m.group(1), 'value': m.group(2).strip()})
            continue

        m = src.try_match(r'typedef\s+struct\s*\{(.*?)\}\s*(\w+);', re.S)
        if m:
            pieces.append({'kind': 'typedef', 'name': m.group(2), 'body': m.group(1)})
            continue

        # A table: [static] TYPE name[] = { ... \n};
        m = src.try_match(r'(?:(static)\s+)?([\w*]+)\s+(\w+)\[\]\s*=\s*\{(.*?)\n\};\n', re.S)
        if m:
            pieces.append({
                'kind': 'table',
                'static': bool(m.group(1)),
                'type': m.group(2),
                'name': m.group(3),
                'body': m.group(4),
                'comment': comment,
            })
            continue

        # A function: RETTYPE name(args) { ... \n}
        m = src.try_match(r'(RE_UINT32|int)\s+(\w+)\(([^)]*)\)\s*\{(.*?)\n\}\n', re.S)
        if m:
            pieces.append({
                'kind': 'function',
                'ret': m.group(1),
                'name': m.group(2),
                'args': m.group(3),
                'body': m.group(4),
                'comment': comment,
            })
            continue

        src.fail('unrecognised top-level construct')

    return pieces


# --------------------------------------------------------------------------------------
# Translating a lookup function
# --------------------------------------------------------------------------------------

# Every statement shape the 100 generic functions are built from. Each entry is
# (compiled pattern, formatter). A body line that matches none of them is a hard error.
def _statement_rules():
    def table(name: str) -> str:
        return pascal(name)

    return [
        (re.compile(r'RE_UINT32 (field_2|field_1|field_0|offset|v);'),
         lambda m: f'uint {m.group(1)};'),
        (re.compile(r'(field_2|field_1|field_0|offset|v) = codepoint >> (\d+);'),
         lambda m: f'{m.group(1)} = codepoint >> {m.group(2)};'),
        (re.compile(r'(field_2|field_1|field_0|offset|v) = \(codepoint >> (\d+)\) & (0x[0-9A-Fa-f]+);'),
         lambda m: f'{m.group(1)} = (codepoint >> {m.group(2)}) & {m.group(3)};'),
        (re.compile(r'(field_2|field_1|field_0|offset|v) = codepoint & (0x[0-9A-Fa-f]+);'),
         lambda m: f'{m.group(1)} = codepoint & {m.group(2)};'),
        # ReadOnlySpan<T>'s indexer takes an int, where a C array takes any integral type,
        # so an index computed in uint needs an explicit cast. Every index here is far below
        # int.MaxValue: the widest is codepoint >> 10, at most 0x43F.
        (re.compile(r'v = (\w+)\[(field_2|field_1|field_0)\];'),
         lambda m: f'v = {table(m.group(1))}[(int){m.group(2)}];'),
        (re.compile(r'v = (\w+)\[\(v << (\d+)\) \| (field_1|field_0)\];'),
         lambda m: f'v = {table(m.group(1))}[(int)((v << {m.group(2)}) | {m.group(3)})];'),
        # C# demands an int shift count where C takes any integral type.
        (re.compile(r'return \(v >> offset\) & (0x[0-9A-Fa-f]+);'),
         lambda m: f'return (v >> (int)offset) & {m.group(1)};'),
        (re.compile(r'return v;'), lambda m: 'return v;'),
        (re.compile(r'return (\d+);'), lambda m: f'return {m.group(1)};'),
        (re.compile(r'if \((0x[0-9A-Fa-f]+) <= codepoint && codepoint <= (0x[0-9A-Fa-f]+)\)'),
         lambda m: f'if ({m.group(1)} <= codepoint && codepoint <= {m.group(2)})'),
        (re.compile(r'if \(codepoint == (0x[0-9A-Fa-f]+)\)'),
         lambda m: f'if (codepoint == {m.group(1)})'),
    ]


STATEMENT_RULES = _statement_rules()


def _translate_statement(name: str, line: str) -> str:
    for pattern, fmt in STATEMENT_RULES:
        m = pattern.fullmatch(line)
        if m:
            return fmt(m)
    raise Fail(f'{name}: unrecognised statement {line!r}')


def translate_function(piece: dict) -> list[str]:
    """Translates one generic lookup function into C#."""
    name = piece['name']
    if piece['args'].strip() != 'RE_UINT32 codepoint':
        raise Fail(f'{name}: unexpected signature {piece["args"]!r}')
    if piece['ret'] != 'RE_UINT32':
        raise Fail(f'{name}: unexpected return type {piece["ret"]}')

    out = [f'    /// <summary>Upstream <c>{name}</c>.</summary>',
           f'    internal static uint {pascal(name)}(uint codepoint)', '    {']
    indent = '        '
    raw_lines = [raw.strip() for raw in piece['body'].split('\n')]
    i = 0
    while i < len(raw_lines):
        line = raw_lines[i]
        i += 1
        if not line:
            if out and out[-1] not in ('', '    {'):
                out.append('')
            continue
        translated = _translate_statement(name, line)
        if line.startswith('if ('):
            # C allows a bare statement after `if (...)`; the codebase always braces.
            while i < len(raw_lines) and not raw_lines[i]:
                i += 1
            if i >= len(raw_lines):
                raise Fail(f'{name}: `if` with no consequent')
            consequent = _translate_statement(name, raw_lines[i])
            i += 1
            out.append(indent + translated)
            out.append(indent + '{')
            out.append(indent + '    ' + consequent)
            out.append(indent + '}')
            continue
        out.append(indent + translated)
    while out and out[-1] == '':
        out.pop()
    out.append('    }')
    return out


# --------------------------------------------------------------------------------------
# Emitting tables
# --------------------------------------------------------------------------------------

def emit_scalar_table(piece: dict):
    """A RE_UINT8 or RE_UINT16 table. Returns the C# lines, the element count and the index."""
    values = split_values(piece['body'])
    name = pascal(piece['name'])
    lines = []
    if piece['comment']:
        lines.append(f'    // {piece["comment"]}')
    if piece['type'] == 'RE_UINT8':
        # A ReadOnlySpan<byte> over a literal is emitted as RVA static data: no allocation,
        # no static constructor, and the JIT can fold the bounds check.
        lines.append(f'    internal static ReadOnlySpan<byte> {name} =>')
        lines.append('    [')
        lines.extend(_wrap(values, 16, '        '))
        lines.append('    ];')
    elif piece['type'] == 'RE_UINT16':
        # ReadOnlySpan RVA data is byte-only, so a 16-bit table is a static array. Roslyn
        # still emits it as a metadata blob plus RuntimeHelpers.InitializeArray, which
        # handles endianness, rather than as element-wise stores.
        lines.append(f'    internal static readonly ushort[] {name} = new ushort[]')
        lines.append('    {')
        lines.extend(_wrap(values, 12, '        '))
        lines.append('    };')
    else:
        raise Fail(f'{piece["name"]}: unexpected scalar table type {piece["type"]}')
    return lines, len(values), [(piece['name'], name)]


def _wrap(values: list[str], per_line: int, indent: str) -> list[str]:
    out = []
    for i in range(0, len(values), per_line):
        out.append(indent + ', '.join(values[i:i + per_line]) + ',')
    return out


def emit_strings(piece: dict) -> tuple[list[str], int]:
    values = re.findall(r'"((?:[^"\\]|\\.)*)"', piece['body'])
    for value in values:
        # C and C# escapes agree on the plausible set, but nothing in these names should
        # need escaping at all, so anything that does is a shape we have not seen.
        if '\\' in value:
            raise Fail(f're_strings: {value!r} contains an escape')
    lines = [
        '    /// <summary>Upstream <c>re_strings</c>: the property and value names.</summary>',
        '    internal static readonly string[] Strings = new string[]', '    {']
    for v in values:
        lines.append(f'        "{v}",')
    lines.append('    };')
    return lines, len(values), []


def emit_struct_table(piece: dict, fields: list[tuple[str, str, int]]) -> tuple[list[str], int]:
    """A struct array, emitted as one flat array per field.

    Naming each field's array after the field makes an accidental field-order swap - the
    classic transliteration bug in a struct table - impossible to write.
    """
    rows = _parse_struct_rows(piece['body'])
    lines: list[str] = []
    index: list[tuple[str, str]] = []
    if piece['comment']:
        lines.append(f'    // {piece["comment"]}')
    for column, (c_field, cs_field, cs_type, arity) in enumerate(fields):
        flat: list[str] = []
        for row in rows:
            cell = row[column]
            if len(cell) > arity:
                raise Fail(f'{piece["name"]}: {c_field} has {len(cell)} values, max {arity}')
            # C zero-fills a partly initialised aggregate.
            flat.extend(cell + ['0'] * (arity - len(cell)))
        member = pascal(piece['name']) + cs_field
        suffix = f' (stride {arity})' if arity > 1 else ''
        lines.append(f'    // {piece["name"]}[].{c_field}{suffix}')
        lines.append(f'    internal static readonly {cs_type}[] {member} = new {cs_type}[]')
        lines.append('    {')
        lines.extend(_wrap(flat, 12, '        '))
        lines.append('    };')
        index.append((f'{piece["name"]}.{c_field}', member))
    return lines, len(rows), index


def _parse_struct_rows(body: str) -> list[list[list[str]]]:
    """``{ 1, { 454, 0}},`` -> ``[['1'], ['454', '0']]`` per row."""
    rows = []
    for raw in body.split('\n'):
        # `{ 195,  0,  0}, /* ALPHABETIC */` - the trailing comment names the entry, which
        # re_strings already carries, so it is dropped.
        line = re.sub(r'/\*.*?\*/', '', raw).strip().rstrip(',')
        if not line:
            continue
        if not (line.startswith('{') and line.endswith('}')):
            raise Fail(f'unexpected struct row {raw!r}')
        inner = line[1:-1]
        cells: list[list[str]] = []
        depth = 0
        current = ''
        for ch in inner:
            if ch == '{':
                depth += 1
                if depth == 1:
                    current = ''
                    continue
            if ch == '}':
                depth -= 1
                if depth == 0:
                    cells.append(split_values(current))
                    current = ''
                    continue
            if ch == ',' and depth == 0:
                if current.strip():
                    cells.append(split_values(current))
                current = ''
                continue
            current += ch
        if current.strip():
            cells.append(split_values(current))
        rows.append(cells)
    return rows


# --------------------------------------------------------------------------------------
# The generator
# --------------------------------------------------------------------------------------

# Which output file each top-level name goes to.
def area_of(name: str) -> str:
    if name in ('re_strings', 're_properties', 're_property_values'):
        return 'PropertyNames'
    if 'all_cases' in name or 'simple_folding' in name or 'full_folding' in name \
            or 'expand_on_folding' in name or 'case_folding' in name:
        return 'Casing'
    if name.startswith('script_extensions'):
        return 'ScriptExtensions'
    return 'Properties'


# The struct arrays, whose fields we split into one flat array each:
# (field name in the C struct, C# member suffix, C# element type, slots the C declaration gives).
PROPERTY_FIELDS = [('name', 'Name', 'ushort', 1), ('id', 'Id', 'byte', 1),
                   ('value_set', 'ValueSet', 'byte', 1)]
PROPERTY_VALUE_FIELDS = [('name', 'Name', 'ushort', 1), ('value_set', 'ValueSet', 'byte', 1),
                         ('id', 'Id', 'ushort', 1)]
ALL_CASES_FIELDS = [('delta', 'Delta', 'uint', 1), ('others', 'Others', 'ushort', 3)]
FULL_FOLDING_FIELDS = [('data', 'Data', 'ushort', 3)]


def build() -> tuple[dict[str, str], dict]:
    defines, externs = parse_header(H_PATH)
    pieces = parse_source(C_PATH)

    # --- constants -------------------------------------------------------------------
    const_lines: list[str] = []
    known: dict[str, str] = {}
    for c_name, value in defines + [(p['name'], p['value']) for p in pieces if p['kind'] == 'define']:
        cs = const_name(c_name)
        known[c_name] = cs
        if value.startswith('"'):
            const_lines.append(f'    /// <summary>Upstream <c>{c_name}</c>.</summary>')
            const_lines.append(f'    internal const string {cs} = {value};')
            continue
        expr = re.sub(r'\bRE_\w+\b', lambda m: known.get(m.group(0), m.group(0)), value)
        if 'RE_' in expr or re.fullmatch(r'[\w\s()|<>&+^*/-]+', expr) is None:
            raise Fail(f'{c_name}: unexpected constant expression {value!r} -> {expr!r}')
        # Every numeric constant is `int`. They all fit (the widest is RE_PROP_C_MASK,
        # 0x30020003), and `int` keeps `1 << PropZl` legal: C# demands an `int` shift count.
        const_lines.append(f'    /// <summary>Upstream <c>{c_name}</c>.</summary>')
        const_lines.append(f'    internal const int {cs} = {expr};')

    # --- everything else -------------------------------------------------------------
    areas: dict[str, list[str]] = {'Properties': [], 'Casing': [], 'ScriptExtensions': [],
                                   'PropertyNames': []}
    stats = {'tables': {}, 'functions': [], 'handPorted': [], 'typedefs': []}
    # (fixture key, C# member) for every numeric table, in file order. The fixture key is the C
    # name, suffixed with the struct field where one table became several.
    index: list[tuple[str, str]] = []
    property_functions: list[str] | None = None

    for piece in pieces:
        kind = piece['kind']
        if kind == 'define':
            continue
        if kind == 'typedef':
            stats['typedefs'].append(piece['name'])
            continue

        if kind == 'table':
            name = piece['name']
            area = area_of(name)
            if name == 're_strings':
                lines, count, entries = emit_strings(piece)
            elif name == 're_properties':
                lines, count, entries = emit_struct_table(piece, PROPERTY_FIELDS)
            elif name == 're_property_values':
                lines, count, entries = emit_struct_table(piece, PROPERTY_VALUE_FIELDS)
            elif piece['type'] == 'RE_AllCases':
                lines, count, entries = emit_struct_table(piece, ALL_CASES_FIELDS)
            elif piece['type'] == 'RE_FullCaseFolding':
                lines, count, entries = emit_struct_table(piece, FULL_FOLDING_FIELDS)
            elif piece['type'] == 'RE_GetPropertyFunc':
                property_functions = split_values(piece['body'])
                stats['tables'][name] = len(property_functions)
                continue
            else:
                lines, count, entries = emit_scalar_table(piece)
            index.extend(entries)
            stats['tables'][name] = count
            areas[area].extend(lines)
            areas[area].append('')
            continue

        if kind == 'function':
            name = piece['name']
            short = name[3:] if name.startswith('re_') else name
            if short in HAND_PORTED:
                digest = body_digest(piece['body'])
                if digest != HAND_PORTED[short]:
                    raise Fail(
                        f'{name}: upstream changed this function. UnicodeCasing.cs hand-ports it, '
                        f'so read the upstream diff, update the C# and re-pin the digest here:\n'
                        f"    '{short}': '{digest}',")
                stats['handPorted'].append(name)
                areas[area_of(name.replace('re_get_', ''))].append(
                    f'    // {name} is hand-ported in UnicodeCasing.cs: its body does not fit the '
                    'three-level-walk shape.')
                areas[area_of(name.replace('re_get_', ''))].append('')
                continue
            areas['Properties'].extend(translate_function(piece))
            areas['Properties'].append('')
            stats['functions'].append(name)
            continue

        raise Fail(f'unhandled piece {kind}')

    if property_functions is None:
        raise Fail('re_get_property table not found')

    # --- the property dispatch switch ------------------------------------------------
    dispatch = [
        "    /// <summary>The number of entries in upstream's <c>re_get_property</c> table.</summary>",
        f'    internal const int PropertyFunctionCount = {len(property_functions)};',
        '',
        '    /// <summary>Upstream <c>re_get_property[prop](codepoint)</c>.</summary>',
        '    internal static uint GetProperty(uint prop, uint codepoint) => prop switch',
        '    {',
    ]
    null_slots = []
    for slot, fn in enumerate(property_functions):
        if fn == '0':
            # Upstream leaves RE_PROP_SCX's slot NULL: script extensions are many-valued, so
            # unicode_has_property branches to re_get_script_extensions before it ever indexes
            # this table. Calling through the NULL is undefined behaviour in C; here it throws.
            null_slots.append(slot)
            dispatch.append(f'        {slot} => throw new InvalidOperationException('
                            f'"property {slot} is many-valued: use GetScriptExtensions"),')
            continue
        short = fn[3:] if fn.startswith('re_') else fn
        if short in HAND_PORTED:
            raise Fail(f'{fn} is in the dispatch table but hand-ported')
        dispatch.append(f'        {slot} => {pascal(fn)}(codepoint),')
    # Upstream's callers range-check `prop` before indexing, so nothing should reach here.
    dispatch.append('        _ => throw new ArgumentOutOfRangeException(nameof(prop)),')
    dispatch.append('    };')
    if null_slots != [86]:
        raise Fail(f'unexpected NULL slots in re_get_property: {null_slots}')
    areas['Properties'].extend([''] + dispatch)

    # --- the table index, for the fixture test ---------------------------------------
    accessor = [
        '    /// <summary>',
        '    /// Every numeric table, keyed by its name in the C source, so a test can walk them',
        '    /// all and check each one against a digest taken independently from that source.',
        '    /// A table that was one struct array in C appears once per field.',
        '    /// </summary>',
        '    /// <returns>The tables, in the order the C file declares them.</returns>',
        '    internal static List<(string Name, uint[] Values)> AllTables()',
        '    {',
        f'        List<(string Name, uint[] Values)> tables = new({len(index)});',
    ]
    for key, member in index:
        accessor.append(f'        tables.Add(("{key}", ToValues({member})));')
    accessor.extend([
        '        return tables;',
        '    }',
        '',
        '    private static uint[] ToValues(ReadOnlySpan<byte> table)',
        '    {',
        '        uint[] values = new uint[table.Length];',
        '        for (int i = 0; i < table.Length; i++)',
        '        {',
        '            values[i] = table[i];',
        '        }',
        '',
        '        return values;',
        '    }',
        '',
        '    private static uint[] ToValues(ushort[] table)',
        '    {',
        '        uint[] values = new uint[table.Length];',
        '        for (int i = 0; i < table.Length; i++)',
        '        {',
        '            values[i] = table[i];',
        '        }',
        '',
        '        return values;',
        '    }',
        '',
        '    private static uint[] ToValues(byte[] table)',
        '    {',
        '        uint[] values = new uint[table.Length];',
        '        for (int i = 0; i < table.Length; i++)',
        '        {',
        '            values[i] = table[i];',
        '        }',
        '',
        '        return values;',
        '    }',
        '',
        '    private static uint[] ToValues(uint[] table) => (uint[])table.Clone();',
    ])

    files = {}
    for area, lines in areas.items():
        text = HEADER.format(ext='c', ns=NAMESPACE, cls=CLASS)
        body = '\n'.join(lines).rstrip('\n')
        files[f'Unicode{area}.g.cs'] = text + body + '\n' + FOOTER

    const_text = HEADER.format(ext='h', ns=NAMESPACE, cls=CLASS)
    files['UnicodeConstants.g.cs'] = const_text + '\n'.join(const_lines) + '\n' + FOOTER
    files['UnicodeTableIndex.g.cs'] = (HEADER.format(ext='c', ns=NAMESPACE, cls=CLASS)
                                       + '\n'.join(accessor) + '\n' + FOOTER)

    stats['externs'] = externs
    stats['index'] = index
    stats['propertyFunctionCount'] = len(property_functions)
    return files, stats


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true',
                        help='fail if the committed files differ from what would be written')
    args = parser.parse_args()

    files, stats = build()

    # Consumption assertions: everything the header declares must have been emitted, at the
    # length the header declares. A silently dropped or truncated table is the failure this
    # whole script exists to make impossible.
    for extern, length in stats['externs'].items():
        if extern not in stats['tables']:
            raise Fail(f'{extern} is declared in the header but was not emitted')
        if stats['tables'][extern] != length:
            raise Fail(f'{extern}: header declares {length} entries, emitted '
                       f'{stats["tables"][extern]}')
    total_functions = len(stats['functions']) + len(stats['handPorted'])
    if total_functions != 104:
        raise Fail(f'expected 104 lookup functions, consumed {total_functions}')
    if sorted(n[3:] for n in stats['handPorted']) != sorted(HAND_PORTED):
        raise Fail(f'hand-ported set changed: {stats["handPorted"]}')
    if len(stats['tables']) != 253:
        raise Fail(f'expected 253 tables, consumed {len(stats["tables"])}')

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    changed = []
    for name, text in files.items():
        path = OUT_DIR / name
        existing = path.read_text(encoding='utf-8') if path.exists() else None
        if existing != text:
            changed.append(name)
            if not args.check:
                path.write_text(text, encoding='utf-8', newline='\n')

    if args.check:
        if changed:
            print('transliterate-unicode: OUT OF DATE - ' + ', '.join(changed), file=sys.stderr)
            return 1
        print('transliterate-unicode: up to date')
        return 0

    total_elements = sum(stats['tables'].values())
    print(f'tables:    {len(stats["tables"])} ({total_elements} elements)')
    print(f'functions: {len(stats["functions"])} transliterated, '
          f'{len(stats["handPorted"])} hand-ported')
    print(f'files:     {", ".join(sorted(files))}')
    if changed:
        print('changed:   ' + ', '.join(sorted(changed)))
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except Fail as exc:
        print(f'transliterate-unicode: {exc}', file=sys.stderr)
        sys.exit(2)
